[motor]
serial_port="/dev/ttyS2"
baudrate=115200

[joystick]
path="/dev/input/js0"

[joymap]
[joymap.axis.throttle]
axis=0
value=1
lin_map_min=0
lin_map_max=100

[joymap.axis.brake]
axis=1
value=0
lin_map_min=0
lin_map_max=100

[joymap.axis.steering]
axis=0
value=0
lin_map_min=-100
lin_map_max=100

[joymap.axis.dpad_horiz]
axis=1
value=1
lin_map_min=-1
lin_map_max=1

[joymap.axis.dpad_vert]
axis=2
value=0
lin_map_min=-1
lin_map_max=1

[joymap.buttons]
cross=0
square=1
circle=2
triangle=3
paddle_right=4
paddle_left=5
r2=6
l2=7
select=8
start=9
r3=10
l3=11
shift_down=12
shift_up=13